name: Hello world

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: |
          echo "Hello worldsss"
  
  add-pending-check:
    if: github.event.action == 'synchronize' && contains(github.event.pull_request.labels.*.name, 'review-app')
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Add pending check until automation test run is finished
        run: |
          curl -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            --url https://api.github.com/repos/Orfium/${{ github.event.repository.name }}/statuses/${{ github.event.pull_request.head.sha }} \
            -d '{"state": "pending", "context": "Jenkins Tests", "description": "Waiting for automation-tests results ", "target_url": "https://jenkins.ci-prod.orfium.xyz/view/CATALOG/job/Music_Rights_Cloud/job/Automation_Tests_Pipeline/"}'